/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierRole;

import Business.Business;
import Business.Organization.Organization;
import Business.Organization.SalesSpecialistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnrollmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Praneeth Reddy
 */
public class EnrollmentRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Business business;
    /**
     * Creates new form EnrolmentRequestJPanel
     */
    public EnrollmentRequestJPanel(JPanel upc, UserAccount userAccount, Business business) {
       initComponents();
       userProcessContainer = upc;
       this.userAccount = userAccount;
       this.business = business;
        populateTable();
    }
    
    private void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel)tblReqStatus.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest wr: userAccount.getWorkQueue().getWorkRequests()){
            Object[] row = new Object[5];
            
            row[0] = wr.getReceiver()==null?"To be Assigned":wr.getReceiver();
            row[1] = wr.getStatus();
            row[2] = wr.getRequestDate();
            row[3] = wr.getResolveDate()==null?"To be Resolved":wr.getResolveDate();
            EnrollmentWorkRequest ewr = (EnrollmentWorkRequest)wr;
            row[4] = ewr.getEnrollmentStatus()==null?"Response Awaited":ewr.getEnrollmentStatus();
            
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReqStatus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        txtReqMsg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        tblReqStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receiver", "Status", "Request Date", "Resolve Date", "Resp Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReqStatus);
        if (tblReqStatus.getColumnModel().getColumnCount() > 0) {
            tblReqStatus.getColumnModel().getColumn(0).setResizable(false);
            tblReqStatus.getColumnModel().getColumn(1).setResizable(false);
            tblReqStatus.getColumnModel().getColumn(2).setResizable(false);
            tblReqStatus.getColumnModel().getColumn(3).setResizable(false);
            tblReqStatus.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Request for Enrollment");

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        jLabel2.setText("Request Message");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRequest)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addComponent(txtReqMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReqMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRequest)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)tblReqStatus.getModel();
        
        int count = dtm.getRowCount();
        
        if(count>=1){
            JOptionPane.showMessageDialog(null,"Request has already been submitted.");
            return;
        }
        String reqMessage = txtReqMsg.getText().trim();
        
        if(reqMessage.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter a message for approval.");
            return;
        }
        
        EnrollmentWorkRequest enrollReq = new EnrollmentWorkRequest();
        enrollReq.setSender(userAccount);
        enrollReq.setStatus(WorkRequest.Status.SENT.getValue());
        enrollReq.setMessage(reqMessage);
        enrollReq.getRequestDate();
        
        Organization org = null;
        
        for(Organization o: business.getOrganizationDirectory().getOrganizationDirectory()){
            if(o instanceof SalesSpecialistOrganization){
                org=o;
                break;
            }
        }
        
        userAccount.getWorkQueue().getWorkRequests().add(enrollReq);
        if(org!=null)
        org.getWorkQueue().getWorkRequests().add(enrollReq);
        
        populateTable();
    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReqStatus;
    private javax.swing.JTextField txtReqMsg;
    // End of variables declaration//GEN-END:variables
}
