/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package UserInterface.SupplierRole;

import Business.Business;
import Business.Employee.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rushabh
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Supplier supplier;
    private UserAccount userAccount;
    private Business business;

    
    /** Creates new form ProductManagerWorkAreaJPanel */
    public SupplierWorkAreaJPanel(JPanel upc, UserAccount ua,Business business) {

        initComponents();
       userProcessContainer = upc;
       supplier = (Supplier)ua.getEmployee();
       userAccount = ua;
       this.business = business;
       boolean check = supplier.checkForEnrollment(userAccount);
       if(!check){
           btnManageProd.setEnabled(false);
           btnReviewProd.setEnabled(false);
           txtSuplierState.setText("You are yet to be Enrolled");
       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageProd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnReviewProd = new javax.swing.JButton();
        btnEnrollSupp = new javax.swing.JButton();
        txtSuplierState = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area (Product Manager Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnManageProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageProd.setText("Manage Product Catalog >>");
        btnManageProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProdActionPerformed(evt);
            }
        });
        add(btnManageProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Update Personal Profile >>");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Manage Staff");
        jButton3.setEnabled(false);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btnReviewProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReviewProd.setText("Review Product Performance >>");
        btnReviewProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewProdActionPerformed(evt);
            }
        });
        add(btnReviewProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        btnEnrollSupp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEnrollSupp.setText("Enroll For Supplier Satus >>");
        btnEnrollSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollSuppActionPerformed(evt);
            }
        });
        add(btnEnrollSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        txtSuplierState.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        txtSuplierState.setForeground(new java.awt.Color(204, 0, 0));
        txtSuplierState.setText("Verified Supplier ™");
        add(txtSuplierState, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, 20));
    }// </editor-fold>//GEN-END:initComponents
    private void btnManageProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProdActionPerformed
        // TODO add your handling code here:
       ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(userProcessContainer, supplier);
        userProcessContainer.add("ManageProductCatalogJPanel",mpcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageProdActionPerformed

    private void btnReviewProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewProdActionPerformed
        // TODO add your handling code here:
        ProductReportJPanel prjp = new ProductReportJPanel(userProcessContainer, supplier);
        userProcessContainer.add("ProductReportJPanelSupplier", prjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReviewProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEnrollSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollSuppActionPerformed
        // TODO add your handling code here:
        EnrollmentRequestJPanel panel = new EnrollmentRequestJPanel(userProcessContainer, userAccount,business);
        userProcessContainer.add("EnrollmentRequestJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnrollSuppActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrollSupp;
    private javax.swing.JButton btnManageProd;
    private javax.swing.JButton btnReviewProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtSuplierState;
    // End of variables declaration//GEN-END:variables
}
