/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdminstrativeRole;

import Business.Business;
import Business.Employee.Customer;
import Business.Organization.Organization;
import Business.Employee.Employee;
import Business.Role.Role;
import Business.Employee.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Praneeth Reddy
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    
    /**
     * Creates new form AddUserAccountJPanel
     */
    public AddUserAccountJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateOrganization();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        activeRadio = new javax.swing.JRadioButton();
        disabledRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox();
        personCmb = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox();

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Add User Account");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Status");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(activeRadio);
        activeRadio.setSelected(true);
        activeRadio.setText("Active");

        buttonGroup1.add(disabledRadio);
        disabledRadio.setText("Disabled");

        jLabel5.setText("Role");

        jLabel6.setText("Person");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        cmbRole.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbRolePropertyChange(evt);
            }
        });

        personCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Organization");

        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backBtn)
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(activeRadio)
                            .addComponent(disabledRadio)
                            .addComponent(cmbOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(submitBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(activeRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disabledRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(personCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String uName = usernameTxt.getText().trim();
        String password = passwordTxt.getText().trim();
        
        if(uName.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a value");
            return;
        }

        if(uName.equalsIgnoreCase("Admin")){
            JOptionPane.showMessageDialog(null, "Admin already exists. Admin can't be duplicate");
            return;
        }
         Employee person = (Employee)personCmb.getSelectedItem();
        if(person==null){
            JOptionPane.showMessageDialog(null, "Please create an Employee.", "Warning Message", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for(Organization org: business.getOrganizationDirectory().getOrganizationDirectory()){
            for(UserAccount ua: org.getUserAccountDirectory().getUserAccountDirectory()){
                if(ua.getUserName().equals(uName)){
                    JOptionPane.showMessageDialog(null, "UserAccount already exists. Please try another Name.");
                    return;
                }
            }
        }
        UserAccount userAccount=null;
        Role role = (Role)cmbRole.getSelectedItem();
        Organization o = (Organization) cmbOrganization.getSelectedItem();
        if(o!=null){
             userAccount = o.getUserAccountDirectory().addAccount();
             userAccount.setUserName(uName);
             userAccount.setPassword(password);
        
        if(role.toString().equals(Role.RoleType.Customer.getValue())){
        Customer customer = (Customer) personCmb.getSelectedItem();
        userAccount.setEmployee(customer);
        }
        if( role.toString().equals(Role.RoleType.Supplier.getValue())){
            Supplier supplier = (Supplier) personCmb.getSelectedItem();
            userAccount.setEmployee(supplier);
        } else {
        }
        userAccount.setRole(role);
        if(activeRadio.isSelected())
               userAccount.setStatus("Active");
        else
               userAccount.setStatus("Disabled");
        JOptionPane.showMessageDialog(null, "UserAccount has been created for: "+userAccount.getUserName());
        usernameTxt.setText("");
        passwordTxt.setText("");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void cmbRolePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbRolePropertyChange
        // TODO add your handling code here:
         //populateCombo();
    }//GEN-LAST:event_cmbRolePropertyChange

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        // TODO add your handling code here:
       Organization o = (Organization) cmbOrganization.getSelectedItem();
        if(o!=null){
            populateCombo(o);
            populateRole(o);
        }
    }//GEN-LAST:event_cmbOrganizationActionPerformed

    private void populateCombo(Organization organization){
        if(cmbRole.getSelectedItem() == null){
            return;
        }
        personCmb.removeAllItems();
        for (Employee person : organization.getEmployeeDirectory().getEmployeeList()) {
            personCmb.addItem(person);
        }

    }
    
    private void populateRole(Organization organization){
        if(cmbOrganization.getSelectedItem() == null){
            return;
        }
        cmbRole.removeAllItems();
        for(Role role : organization.getSupportedRole()){
            cmbRole.addItem(role);
        }
    }
    
    private void populateOrganization(){
        cmbOrganization.removeAllItems();            
        for(Organization organization : business.getOrganizationDirectory().getOrganizationDirectory()){
            cmbOrganization.addItem(organization);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadio;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JRadioButton disabledRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JComboBox personCmb;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
