/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.AdminstrativeRole;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  Rushabh
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel upc,Business business) {
        initComponents();
        userProcessContainer = upc;
        this.business = business;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageAccountsButton = new javax.swing.JButton();
        managesuppliersButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        manageAccountsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageAccountsButton.setText("Manage UserAccounts >>");
        manageAccountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountsButtonActionPerformed(evt);
            }
        });
        add(manageAccountsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 260, -1));

        managesuppliersButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        managesuppliersButton1.setText("Manage Employee >>");
        managesuppliersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managesuppliersButton1ActionPerformed(evt);
            }
        });
        add(managesuppliersButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageAccountsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountsButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel panel = new ManageUserAccountJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageCustomers", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAccountsButtonActionPerformed

    private void managesuppliersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managesuppliersButton1ActionPerformed
        // TODO add your handling code here:
        ManageEmployee panel = new ManageEmployee(userProcessContainer,business);
        userProcessContainer.add("ManageEmployee", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managesuppliersButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAccountsButton;
    private javax.swing.JButton managesuppliersButton1;
    // End of variables declaration//GEN-END:variables
    
}
