/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SalesSpecialistRole;

import Business.Business;
import Business.Organization.Organization;
import Business.Organization.SalesSpecialistOrganization;
import Business.Organization.ShippingSpecialistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Praneeth Reddy
 */
public class ProcessOrderShippingPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SalesSpecialistOrganization sso;
    private Business business;
    /**
     * Creates new form ProcessOrderShippingPanel
     */
    public ProcessOrderShippingPanel(JPanel userProcessContainer,UserAccount userAccount,SalesSpecialistOrganization sso,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.sso = sso;
        this.business = business;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblOrderApproval.getModel();
        
        dtm.setRowCount(0);
        
        for(WorkRequest wr: sso.getWorkQueue().getWorkRequests()){
            if(wr instanceof OrderWorkRequest){
            Object[] row = new Object[6];
            
            row[0] = wr.getSender();
            row[1] = wr.getReceiver()==null?"To be Assigned":wr.getReceiver();
            row[2] = wr.getStatus();
            row[3] = wr.getRequestDate();
            row[4] = wr.getResolveDate()==null?"To be Resolved":wr.getResolveDate();
            row[5] = wr;
            
            dtm.addRow(row);
        }
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderApproval = new javax.swing.JTable();
        btnSelfAssign = new javax.swing.JButton();
        btnApprovalOrd = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        txtApproval = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Approve Orders For Shipping");

        tblOrderApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Status", "Req Date", "Res Date", "Msg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderApproval);

        btnSelfAssign.setText("Self-Assign");
        btnSelfAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelfAssignActionPerformed(evt);
            }
        });

        btnApprovalOrd.setText("Approve Order");
        btnApprovalOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovalOrdActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Approval Msg:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnSelfAssign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprovalOrd))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelfAssign)
                    .addComponent(txtApproval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton)
                    .addComponent(btnApprovalOrd))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelfAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelfAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrderApproval.getSelectedRow();

        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }

        OrderWorkRequest owr = (OrderWorkRequest)tblOrderApproval.getValueAt(selectedRow, 5);
        if(owr.getReceiver() != null || owr.getStatus().equals(WorkRequest.Status.APPROVED.getValue())){
            JOptionPane.showMessageDialog(null, "This Request has already been assigned.");
            return;
        }
        owr.setReceiver(userAccount);
        owr.setStatus(WorkRequest.Status.PENDING.getValue());

        populateTable();
    }//GEN-LAST:event_btnSelfAssignActionPerformed

    private void btnApprovalOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovalOrdActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblOrderApproval.getSelectedRow();

        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }

        String orderStatus = txtApproval.getText().trim();

        if(orderStatus.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a response.");
            return;
        }

        OrderWorkRequest owr = (OrderWorkRequest)tblOrderApproval.getValueAt(selectedRow, 5);
        
        if(owr.getStatus().equals(WorkRequest.Status.SENT.getValue())){
            JOptionPane.showMessageDialog(null, "Assign it to yourself before approving.");
            return;
        }
         if(owr.getStatus().equals(WorkRequest.Status.APPROVED.getValue())){
            JOptionPane.showMessageDialog(null, "This request has been already been Approved & Forwarded to Shipping.");
            return;
        }
        if(!owr.getReceiver().equals(userAccount)){
            JOptionPane.showMessageDialog(null, "This Request is being processed by another Specialist.");
            return;
        }
//        if(owr.getStatus().equals(WorkRequest.Status.APPROVED.getValue())){
//            JOptionPane.showMessageDialog(null, "This request has been processed.");
//            return;
//        }
        owr.setStatus(WorkRequest.Status.APPROVED.getValue());
        owr.setMessage(orderStatus);
        owr.setSender(userAccount);
        owr.setReceiver(null);
        for(Organization orgn: business.getOrganizationDirectory().getOrganizationDirectory()){
            if(orgn instanceof ShippingSpecialistOrganization){
                orgn.getWorkQueue().getWorkRequests().add(owr);
            }
        }
        populateTable();
    }//GEN-LAST:event_btnApprovalOrdActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnApprovalOrd;
    private javax.swing.JButton btnSelfAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrderApproval;
    private javax.swing.JTextField txtApproval;
    // End of variables declaration//GEN-END:variables
}
