/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SalesSpecialistRole;

import Business.Organization.SalesSpecialistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnrollmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Praneeth Reddy
 */
public class ProcessEnrollmentRequestPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SalesSpecialistOrganization sso;
    /**
     * Creates new form ProcessEnrollmentRequestPanel
     */
    public ProcessEnrollmentRequestPanel(JPanel userProcessContainer,UserAccount userAccount, SalesSpecialistOrganization sso) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.sso = sso;
        populateTable();
    }
    
    
    private void populateTable(){
    
        DefaultTableModel dtm = (DefaultTableModel)tblEnrollStatus.getModel();
        
        dtm.setRowCount(0);
        
        for(WorkRequest wr: sso.getWorkQueue().getWorkRequests()){
            if(wr instanceof EnrollmentWorkRequest){
            Object[] row = new Object[6];
            
            row[0] = wr.getSender();
            row[1] = wr.getReceiver()==null?"TO be Assigned":wr.getReceiver();
            row[2] = wr.getStatus();
            row[3] = wr.getRequestDate();
            row[4] = wr.getResolveDate()==null?"To be resolved":wr.getResolveDate();
            row[5] = wr;
            
            dtm.addRow(row);
            }
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrollStatus = new javax.swing.JTable();
        btnSelfAssign = new javax.swing.JButton();
        btnEnrollSupp = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        txtEnrollMsg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Process Enrollment ");

        tblEnrollStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Status", "Req Date", "Res Date", "Req Msg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnrollStatus);

        btnSelfAssign.setText("Self-Assign");
        btnSelfAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelfAssignActionPerformed(evt);
            }
        });

        btnEnrollSupp.setText("Enroll Supplier");
        btnEnrollSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollSuppActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Enrollment Msg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnSelfAssign)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnrollSupp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnrollMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelfAssign)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtEnrollMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnrollSupp)
                    .addComponent(backJButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnSelfAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelfAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEnrollStatus.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
       
        EnrollmentWorkRequest ewr = (EnrollmentWorkRequest)tblEnrollStatus.getValueAt(selectedRow, 5);
        if(ewr.getReceiver() != null){
            JOptionPane.showMessageDialog(null, "This Request has already been assigned.");
            return;
        }
        ewr.setReceiver(userAccount);
        ewr.setStatus(WorkRequest.Status.PENDING.getValue());
        
        populateTable();
    }//GEN-LAST:event_btnSelfAssignActionPerformed

    private void btnEnrollSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollSuppActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblEnrollStatus.getSelectedRow();
        
        if(selectedRow <0){
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        
        String enrollStatus = txtEnrollMsg.getText().trim();
        
        if(enrollStatus.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a response.");
            return;
        }
        
        EnrollmentWorkRequest wr = (EnrollmentWorkRequest)tblEnrollStatus.getValueAt(selectedRow, 5);
        if(wr.getStatus().equals(WorkRequest.Status.SENT.getValue())){
            JOptionPane.showMessageDialog(null, "Assign it to yourself before approving.");
            return;
        }
        if(!wr.getReceiver().equals(userAccount)){
            JOptionPane.showMessageDialog(null, "This Request is being processed by another Sales Specialist.");
            return;
        }
        if(wr.getStatus().equals(WorkRequest.Status.COMPLETED.getValue())){
            JOptionPane.showMessageDialog(null, "This request has been processed.");
            return;
        }
        wr.setStatus(WorkRequest.Status.COMPLETED.getValue());
        wr.setResolveDate(new Date());
        wr.setEnrollmentStatus(enrollStatus);
        wr.setMessage(enrollStatus);
        
        populateTable();
    }//GEN-LAST:event_btnEnrollSuppActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnEnrollSupp;
    private javax.swing.JButton btnSelfAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnrollStatus;
    private javax.swing.JTextField txtEnrollMsg;
    // End of variables declaration//GEN-END:variables
}
